### ISSUE TITLE
Support Jaeger Login/Authentication

### ISSUE THREAD

**Issue by aviranco** [jaegertracing/jaeger-ui#211]
I would like to expose the Jaeger UI with user/password authentication, is it currently possible?
If not, I think it would be really useful so only authorized users can view the logs

**Comment by yurishkuro** [comment]
it is possible, but it's not a function that Jaeger provides directly. At Uber we run Jaeger UI behind an nginx proxy that is integrated with single sign-on.

**Comment by Marusyk** [comment]
any plans to add auth for dashboard?

**Comment by yurishkuro** [comment]
Please see [Issue #1718](https://github.com/jaegertracing/jaeger/issues/1718) for the summary of available security mechanisms in Jaeger.

**Comment by a1300** [comment]
@yurishkuro can you share your nginx revers proxy configuration?
Thanks in advance

**Comment by Marusyk** [comment]
Hi @a1300, I can share mine if it helps

```
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  auth: ZWxhc3RpYzokYXByMSRCMDVsdW1FbSRWNWJkMmVqWE02RXBQVFZWVnVnbE8v
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - ok'
spec:
  tls:
  - hosts:
    - host.com
    secretName: jaeger-crt
  rules:
  - host: host.com
    http:
      paths:
      - path: /jaeger
        backend:
          serviceName: jaeger
          servicePort: 16686
```
