### ISSUE TITLE
Jaeger should have a contextpath and allow to customize

### ISSUE THREAD

**Issue by clyang82** [jaegertracing/jaeger-ui#258]
I have a case to integrate some ui together and expose them by using the same ingress controller. here is an example ingress file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-search-ingress
  namespace: istio-system
  labels:
    app: jaeger
  annotations:
      kubernetes.io/ingress.class: xxx
spec:
  rules:
    - http:
        paths:
          - path: /search
            backend:
              serviceName: jaeger-query
              servicePort: 16686
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-static-ingress
  namespace: istio-system
  labels:
    app: jaeger
  annotations:
      kubernetes.io/ingress.class: xxx
spec:
  rules:
    - http:
        paths:
          - path: /static
            backend:
              serviceName: jaeger-query
              servicePort: 16686
```
from the above example, the path '/static' and '/search' are very common path. if the 2 applications have the same path, we cannot expose them by the same ingress controller. kiali is using 'static' while jaeger is using 'static' as well.

If the application have the contextpath, then we can use the following way to achieve this goal. Take 'jaeger' as an example to explain:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger
  namespace: istio-system
  labels:
    app: jaeger
  annotations:
      kubernetes.io/ingress.class: xxx
      icp.management.ibm.com/rewrite-target: /jaeger
spec:
  rules:
    - http:
        paths:
          - path: /jaeger
            backend:
              serviceName: jaeger-query
              servicePort: 16686
```
so we should have a contextpath for the application. for jaeger application, can we consider to have a contextpath? Thanks.
